community:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: db_community
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tAz4gqh9R1dbEHizSFP
    access-key-secret: UaKuX8zqYJdK4tZ7jS7bG0BtgV5dMV
    bucket-name: web-ao666
  redis:
    host: 8.130.128.161
    port: 6379
    password: 123456
    database: 1